### ISSUE TITLE
Cannot retrieve some datasets (2193, 2194)

### ISSUE THREAD

**Issue by krokkie** [dzulfiqarfr/bpsr#4]
Good day

I have a problem running bpsr::bps_get_dataset("2193").     (And some others too)
I'm getting a "This ID doesn't exist", which is not true.   check_dataset_id fails.
My guess is that this is because the internal cached data is outdated. 
This checking mechanism is not working optimal, as these ID do change regularly, and a package update every time

There are many options to fix this:
1) An function call that updates the internal database.  
    bpsr::update_internal_database()
    This might mean implementing some other mechanism for storing the variables somewhere else - I'm not sure if a package can change itself....

2) Additional skip_check parameter, that is default FALSE for the functions where this check is used.  
    For example bps_get_dataset <- function(..., skip_check=FALSE)

3) Reduce the severity of the check to a warning, not a stop, change the message to:  "The ID appears to be invalid - based on a list of valid IDs that might be slightly outdated by now.   The function will keep trying, and might fail shortly"

Thanks

**Comment by dzulfiqarfr** [comment]
Hi, Gerhard. I have closed this issue after merging your pull request #5. Regardless, I agree with you that the current workflow to cache the list of dataset IDs is far from perfect.

Actually, I've thought about this but haven't had the time to work on the solution. I've been considering adding a function that allows users to update the internal data, which is similar to the first option you suggested. I haven't really thought about the function components, though
